@echo off
cd files
echo oops...
echo 당신의 파일은 NDJ에 의해 암호화 되었습니다.
echo 당신의 컴퓨터는 우리의 툴이 없다면 복구할수 없습니다 (구매링크 바로가기)
echo 중요!
echo 당신이 지불을 망설이는 동안 가격이 올라가고 파일이 삭제됩니다.
echo 암호화가 완료되면 글자색이 변경될것입니다!
ping 127.0.0.1>NUL
echo -------------------------------------------------------
echo 1.이게 무슨소리야?
echo -당신의 컴퓨터의 모든파일은 암호화 되었습니다
echo 2.추가정보
echo -동일한 네트워크에 모든호스트도 암호화 되었습니다
ping 127.0.0.1>NUL
echo -------------------------------------------------------
echo 당신의 네트워크의 복구비용: 0.%random% btc
echo 암호화 시작중....
echo 암호화 대상 디랙터리: files
ping 127.0.0.1>NUL
echo -------------------------------------------------------
echo 참고: 당신의 컴퓨터가 감염된지 10일이 지나면 MBR이 변조되고
echo 11일이 지나면 로우-레벨 포멧되어 컴퓨터를 아예 사용할수없으며
echo o/s를 제설치 하려고한다면 즉시 실행될 것입니다!
echo 암호화 마무리중
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
echo NDJ에 의해 암호화됨 %computername% 당신의 파일은 NDJ에 강력한 보호하에 있으며 파일을 복구하려면 NDJ 인크립터를 실행하십시오.>%random%files.encryption%random%NDJ
color 03
pause